version: '2'

services:
  app:
    image: podsync
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=80
    ports:
      - 80:80
    environment:
      - Podsync:RedisConnectionString=redis
    env_file:
      - ~/podsync.env
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - /data/redis:/data
