version: '2'

services:
  app:
    image: podsync
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5001
    environment:
      - ASPNETCORE_URLS=http://*:5001
      - Podsync:RedisConnectionString=redis
    env_file:
      - ~/podsync.env
  redis:
    image: redis
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - /data/redis:/data
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
