linters:
  presets:
    - bugs
    - unused
    - format
    - style
    - complexity
    - performance
  disable:
    - errcheck
    - gochecknoglobals
issues:
  exclude:
    - if block ends with a return statement, so drop this else and outdent its block