version: 0.2

env:
  variables:
    GO111MODULE: on
  parameter-store:
    YOUTUBE_TEST_API_KEY: "/CodeBuild/youtubeKey"
    VIMEO_TEST_API_KEY: "/CodeBuild/vimeoKey"

phases:
  build:
    commands:
      - make lint
      - make test
