version: 0.2

env:
  variables:
    GO111MODULE: on
  parameter-store:
    YOUTUBE_TEST_API_KEY: "/CodeBuild/youtubeKey"
    VIMEO_TEST_API_KEY: "/CodeBuild/vimeoKey"

phases:
  install:
    commands:
      - go version
      - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b /usr/local/bin v1.12.5
      - golangci-lint --version
  build:
    commands:
      - go test -short ./...
      - golangci-lint run