version: '2.2'

services:
  api:
    image: mxpv/podsync_api
    container_name: api
    restart: always
    ports:
      - 8080:5001
    environment:
      - REDIS_CONNECTION_URL=redis://redis
      - POSTGRES_CONNECTION_URL={POSTGRES_CONNECTION_URL}
      - UPDATER_URL=http://updater:8080/update
      - YOUTUBE_API_KEY={YOUTUBE_API_KEY}
      - VIMEO_API_KEY={VIMEO_API_KEY}
      - PATREON_CLIENT_ID={PATREON_CLIENT_ID}
      - PATREON_SECRET={PATREON_SECRET}
      - PATREON_REDIRECT_URL=https://podsync.net/user/patreon
      - PATREON_WEBHOOKS_SECRET={PATREON_WEBHOOKS_SECRET}
      - COOKIE_SECRET={COOKIE_SECRET}
      - GIN_MODE=release
      - AWS_REGION=us-east-1
      - DYNAMO_FEEDS_TABLE_NAME=Prod_Feeds
      - DYNAMO_PLEDGES_TABLE_NAME=Prod_Pledges
      - UPDATER_SQS_QUEUE_URL={URL}
  redis:
    image: redis:5.0.3
    container_name: redis
    command: redis-server --appendonly yes --save 900 1 --save 300 10 --save 60 10000
    restart: always
    volumes:
      - /data/redis:/data
    sysctls:
      net.core.somaxconn: 1024
  nginx:
    image: mxpv/nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 8081:80
  resolver:
    image: mxpv/resolver:latest
    container_name: resolver
    command: --workers 8
    restart: always
    ports:
      - 8082:8080
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - DYNAMO_FEEDS_TABLE_NAME=Prod_Feeds
      - DYNAMO_RESOLVE_COUNTERS_TABLE=Prod_ResolveCounters
  updater:
    image: mxpv/updater:latest
    restart: always
    scale: 8
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - UPDATER_SQS_QUEUE_URL={URL}
      - DYNAMO_FEEDS_TABLE_NAME=Prod_Feeds
