version: '2'

services:
  app:
    image: gcr.io/pod-sync/app:latest
    container_name: app
    restart: always
    ports:
      - 5001
    environment:
      - REDIS_CONNECTION_URL=redis://redis
      - YOUTUBE_API_KEY={YOUTUBE_API_KEY}
      - VIMEO_API_KEY={VIMEO_API_KEY}
      - PATREON_CLIENT_ID={PATREON_CLIENT_ID}
      - PATREON_SECRET={PATREON_SECRET}
      - PATREON_REDIRECT_URL=http://podsync.net/patreon
      - COOKIE_SECRET={COOKIE_SECRET}
  ytdl:
    image: gcr.io/pod-sync/ytdl:latest
    container_name: ytdl
    restart: always
    ports:
      - 5002
    environment:
      - METADATA_URL=http://app:5001/api/metadata/{feed_id}
  redis:
    image: redis
    container_name: redis
    command: redis-server --appendonly no --save 900 1 --save 300 10 --save 60 10000
    restart: always
    volumes:
      - /data/redis:/data
  nginx:
    image: gcr.io/pod-sync/nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80