
[[constraint]]
  name = "github.com/mxpv/podcast"
  branch = "master"

[[constraint]]
  name = "github.com/speps/go-hashids"
  revision = "c6ced3330f133cec79e144fb11b2e4c5154059ae"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2"

[[constraint]]
  name = "github.com/gin-contrib/sessions"
  revision = "a71ea9167c616cf9f02bc928ed08bc390c8279bc"

[[constraint]]
  name = "github.com/mxpv/patreon-go"
  version = "1.2"