
[[constraint]]
  name = "github.com/mxpv/podcast"
  branch = "release"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2"

[[constraint]]
  name = "github.com/gin-contrib/sessions"
  revision = "a71ea9167c616cf9f02bc928ed08bc390c8279bc"

[[constraint]]
  name = "github.com/mxpv/patreon-go"
  version = "1.3"

[[constraint]]
  name = "github.com/ventu-io/go-shortid"
  branch = "master"