version: '2'

services:
  app:
    image: podsync/app
    build:
      context: ./Podsync
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5001
    environment:
      - ASPNETCORE_URLS=http://*:5001
      - Podsync:RedisConnectionString=redis
      - Podsync:RemoteResolverUrl=http://ytdl:8080
    env_file:
      - ~/podsync.env
  ytdl:
    image: podsync/ytdl
    build:
      context: ./ytdl
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080
  redis:
    image: redis
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - /data/redis:/data
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
