name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          make build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        run: |
          make test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint
        run: |
          make lint
